export const productType = {
  GET_PRODUCTS_LIST: 'GET_PRODUCTS_LIST',
  GET_PRODUCTS: 'GET_PRODUCTS',
  ADD_PRODUCT: 'ADD_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  EDIT_PRODUCT: 'EDIT_PRODUCT'
}

export const languageType = {
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  LOAD_TRANSLATIONS: 'LOAD_TRANSLATIONS'
}


export const postType = {
  GET_POST_LIST: 'GET_POST_LIST'
}
